### PR TITLE
feat(security): Set "no-new-privileges" on Svcs

### PR DESCRIPTION
**Pull request by beaufrusetta**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md.

## What is the current behavior?
UIDs within containers running in EdgeX can request and gain elevated privilege which creates a security risk to the processes running within the containers.

## Issue Number:
#143 

## What is the new behavior?
All services, under the orchestration of docker-compose, are now prohibited from gaining elevated privilege through the Docker security option "no-new-privileges" set in the compose service defintions.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?
N/A

## Other information

### CODE REVIEW

**Comment by beaufrusetta** [comment]
Rebased to resolve the conflict behind the scenes...all good to go now.

**Review by bnevis-i — APPROVED** [review]
LGTM.  No explosions.

**Comment by beaufrusetta** [comment]
> LGTM. No **explosions**.

That's always a key component.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@cherrycl , the TAF smoke tests for Core Metadata tests are failing this another PRs. I am pretty sure this is unrelated to these PRs. Do these test fail in the regular TAF tests? THX!
https://github.com/edgexfoundry/developer-scripts/pull/367
https://github.com/edgexfoundry/developer-scripts/pull/368

**Comment by cherrycl** [comment]
@lenny-intel Yes, these tests also failed in functional-test. it has fixed by [edgex-taf PR #249](https://github.com/edgexfoundry/edgex-taf/pull/249) at present.

**Comment by lenny-intel** [comment]
> Yes, these tests also failed in functional-test

Thanks you!

**Comment by lenny-intel** [comment]
recheck

**Pull request merged**
