### PR TITLE
fix: Add separate UI version and registry variables

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md.

## What is the current behavior?
UI compose file uses same version and registry variables as Core services

## What is the new behavior?
UI compose file now uses UI specific version and registry variables

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by jim-wang-intel — CHANGES_REQUESTED** [review]
in `ui-down` of Makefile, i guess it also needs the new envs

**Comment by lenny-intel** [comment]
> in `ui-down` of Makefile, i guess it also needs the new envs

Yep, great catch!

**Comment by lenny-intel** [comment]
> in `ui-down` of Makefile, i guess it also needs the new envs

Actually, not needed since that are in the `.env` file. Anything in the `.env` file is automatically picked up and doesn't need to be passed. But,  `ui-down` does need to be cleaned up to remove those that are not needed.

**Comment by jim-wang-intel** [comment]
> > in `ui-down` of Makefile, i guess it also needs the new envs
> 
> Actually, not needed since that are in the `.env` file. Anything in the `.env` file is automatically picked up and doesn't need to be passed. But, `ui-down` does need to be cleaned up to remove those that are not needed.

ok

**Review by jim-wang-intel — APPROVED** [review]
in `ui-down` of Makefile, i guess it also needs the new envs

**Comment by jim-wang-intel** [comment]
recheck

**Review by jim-wang-intel — APPROVED** [review]

**Comment by cloudxxx8** [comment]
recheck

**Pull request merged**
