### PR TITLE
build(nightly_build): update kuiper version

### PR DESCRIPTION
**Pull request by zhanghongtong**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by lenny-intel — CHANGES_REQUESTED** [review]
These compose files are generated and must not be manually edited. See header.
Changes must be done from developer-scripts/compose-builder source file(s) and then run `make build`  to re-generate this compose files.
https://github.com/edgexfoundry/developer-scripts/blob/master/compose-builder/README.md

**Comment by lenny-intel** [comment]
Also you cimmit /PR tiles don't adhere to our semantic commit message options. See https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md. for more details.

**Comment by zhanghongtong** [comment]
Hi, @lenny-intel I've updated the code, please review again

I updated my commit/PR tiles, but it looks like the check failed, please tell me what to do

**Comment by lenny-intel** [comment]
@zhanghongtong , I think issue is your commit message is just a missing space after `:`.

Also, I just merged a  PR that added more generated compose files for testing. Please rebase your PR and run `make build` once more. THX!

**Comment by zhanghongtong** [comment]
Hi, @lenny-intel 
Thank you for your reply, I've updated the code and commit massage, please review again

**Comment by jinlinGuan** [comment]
@zhanghongtong, could you please `make build` again? The nightly-build taf compose files should also be updated. Thanks.

**Comment by zhanghongtong** [comment]
> @zhanghongtong, could you please `make build` again? The nightly-build taf compose files should also be updated. Thanks.

Hi, @jinlinGuan 

I executed `make build` and pushed a new commmit, but `make build` modified a lot of files, and I'm not sure that's correct.

**Comment by lenny-intel** [comment]
@zhanghongtong,, another issue is the version of docker-compose you are using has a bug in the way it is generating the depends_on sections. I think it is easier if I make the change and generate a new PR.

**Comment by lenny-intel** [comment]
Completed with https://github.com/edgexfoundry/developer-scripts/pull/379

**Comment by zhanghongtong** [comment]
Hi，@lenny-intel

Can you tell me how to avoid making mistakes depends_on when `make build` ? Maybe I can create a new PR

**Comment by lenny-intel** [comment]
Hi, @zhanghongtong , it is just the version of docker-compose you used. The latest has a bug that generates the `depends_on` section incorrectly for the 3.x spec. We use version ` 1.27.2` to avoid this, since it was breaking our tests. The tests scripts previously modified the compose files and expected a specific format which got broken. My recent PR has obsoleted those scripts, so now I think we are ok with using latest compose, but haven't verified it yet.

Nothing for you to do now as I created a PR for your change and it has ben merged.

**Comment by zhanghongtong** [comment]
> Hi, @zhanghongtong , it is just the version of docker-compose you used. The latest has a bug that generates the `depends_on` section incorrectly for the 3.x spec. We use version ` 1.27.2` to avoid this, since it was breaking our tests. The tests scripts previously modified the compose files and expected a specific format which got broken. My recent PR has obsoleted those scripts, so now I think we are ok with using latest compose, but haven't verified it yet.
> 
> Nothing for you to do now as I created a PR for your change and it has ben merged.

Well, I see, thank you for your reply and have a nice day

**Pull request closed without merging**
