### PR TITLE
Bump version of redis container (to 6.0-rc1-alpine)

### LINKED ISSUE #194: Version bump of redis for Geneva
Version bump of redis for Geneva

Cloned from https://github.com/edgexfoundry/edgex-go/issues/1935.

Bump redis version in docker-compose.
Snaps must be similarly updated.

Version bump is needed to pick up security fixes and reduce technical debt from using out-of-date container versions.

Blackbox regressions must be run against new version.

### PR DESCRIPTION
**Pull request by bnevis-i**
Fixes #194 

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

### CODE REVIEW

**Comment by bnevis-i** [comment]
@andresrinivasan are you interested in testing this?

**Comment by bnevis-i** [comment]
> I suggest we stick with Redis 5 until Redis 6.0.1 is released. Besides the usual reasons to not be on the bleeding edge of releases, I haven't thoroughly tested the impact of RESP 3 with the redigo client library.

If Redis 6.0 is going to be released by Geneva code freeze, we should start validating 6.x now -- we don't want to make a major version bump just prior to release.  If it is not going to be released by code freeze we should at least bump to the latest docker hub version.  I would suggest Valentine's day as yardstick measure to go with one version or the other for Gevena release.

> You mention resolving technical debt; can you be more specific?

The technical debt incurred by not making an update is:
- CVEs in the base image that have been discovered since 5.0.5 was released (current docker hub version is now at 5.0.7)
- Fixes made to Redis since 5.0.5 was released
- Lock-in to older versions of servers and/or client libraries by not upgrading to detect breaking changes (see above)

**Comment by andresrinivasan** [comment]
Seems like a reasonable plan.

**Comment by bnevis-i** [comment]
@andresrinivasan Valentine's day has passed.  Ready to make a call?  Are we going with 5.x or 6.x?

**Comment by andresrinivasan** [comment]
Let's go with 5.x.

**Comment by bnevis-i** [comment]
Already at latest version; cancelling PR.

**Pull request closed without merging**
