### PR TITLE
Issue 97 - clean_mongo.js should also remove notification collections

### PR DESCRIPTION
**Pull request by michaelestrin**
Signed-off-by: Michael W. Estrin <me@michaelestrin.com>

#97

### CODE REVIEW

**Comment by tsconn23** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
Could try closing this PR and reopening while we wait for a response from GitHub.

**Comment by michaelestrin** [comment]
Closing and will reopen under new PR to see if that resolves the issue.

**Comment by michaelestrin** [comment]
https://github.com/edgexfoundry/developer-scripts/pull/101

**Pull request closed without merging**
