### PR TITLE
fix: bump Redis from 5.0.8 to 6.0

### PR DESCRIPTION
**Pull request by hutchic**
closes: https://github.com/edgexfoundry/developer-scripts/issues/239

Signed-off-by: Colin Hutchinson <chutchic@gmail.com>

### CODE REVIEW

**Comment by lenny-intel** [comment]
@hutchic , @bnevis-i , In future we should group the issues/PRs into one if doing at the same time to avoid having to fixing conflicts like on this PR. Or one PR addresses multiple issue???

**Comment by bnevis-i** [comment]
@lenny-intel 

I think there is a legitimate way to do what you want without sacrificing anything:

Create a PR with multiple commits that fixes multiple issues.

That way, should it be needed (upgrade of one component succeeded while another failed), a single commit could be reverted.

**Comment by hutchic** [comment]
In an ideal world blackbox tests would run against PR's in this repository but in lieu of that I didn't want the PR's to collide should folks want to validate locally -- aka change one variable at a time in an experiment or you won't know which one broke things ;)

**Review by lenny-intel — APPROVED** [review]
LGTM. Verified `redis:6.0-alpine` exists w/o specifying patch ;-)

**Pull request merged**
