### PR TITLE
feat(security): Remove Vault dependency on Consul

### PR DESCRIPTION
**Pull request by jim-wang-intel**
With the Vault's backend storage been changed to filesystem instead of Consul,  will no longer depend on  in the compose file.

This together with edgex-go's change and edgex-consul's vault healthy check removal shall close the issue edgexfoundry/edgex-go#2882 .

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md.

## What is the current behavior?

Vault depends on Consul

## Issue Number:  
Fixes edgexfoundry/edgex-go#2882

## What is the new behavior?
Vault will not depend on Consul directly

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

**Note:  For this compose up working correctly, it requires the following two PRs merged into master first:**
1. https://github.com/edgexfoundry/edgex-go/pull/2886 
1. https://github.com/edgexfoundry/docker-edgex-consul/pull/40

## Other information
If tested locally, do the following steps:
1. Clone the code from https://github.com/edgexfoundry/edgex-go/pull/2886  
1. Build the latest docker images for `edgex-go`: `make docker`
1. Clone the code from https://github.com/edgexfoundry/docker-edgex-consul/pull/40 
1. Build the latest `edgex-core-consul` docker image: `make docker`
1. Go to `compose-builder` sub-directory and do `make gen dev` to generate the local version of `docker-compose.yml` to run
1. Modify the `edgex-core-consul` docker image in the generated docker-compose file to point to the local built docker image above: 
   ```yaml
   image: edgexfoundry/docker-edgex-consul:0.0.0
   ```
1. In the command-line, run `docker-compose up` and all services should started up ok (can be checked and see using `docker ps` and individual docker logs via portainer).   Also it should be ok in the docker logs `edgex-core-consul`

### CODE REVIEW

**Review by bnevis-i — APPROVED** [review]

**Review by lenny-intel — CHANGES_REQUESTED** [review]
You need to run `make build` so this change is propagated to the generated compose files.
Make sure to use docker-compose version `1.27.2` since newer versions have bug that generated `depends_on` section incorrectly that results in our TAF tests failing.

Also move PR to draft until ADR is approved.

**Comment by jim-wang-intel** [comment]
> You need to run `make build` so this change is propagated to the generated compose files.
good catch. thanks!

> Make sure to use docker-compose version `1.27.2` since newer versions have bug that generated `depends_on` section incorrectly that results in our TAF tests failing.
ok, good to know.

> 
> Also move PR to draft until ADR is approved.

sure.

**Comment by lenny-intel** [comment]
@jim-wang-intel , This change breaks the TAF smoke tests. Likely because the TAF scripts expect the consul line to be their when run `sed`. Please verify by running the initial TAF scripts against your PR. These are the scripts in https://github.com/edgexfoundry/edgex-taf/tree/master/TAF/utils/scripts/docker that pull and modify the compose file. Specifically run `get-compose-file.sh` with it pulling from your branch and verify the resulting compose file is valid syntactically. Likely will require a PR to adjust the TAF script...

**Comment by lenny-intel** [comment]
recheck

**Review by lenny-intel — DISMISSED** [review]
LGTM

**Comment by lenny-intel** [comment]
@cherrycl , can you look at the TAF smoke test failures on this PR? The PR just removes consul from Vault depends_on. THX!

**Comment by cherrycl** [comment]
recheck

**Comment by cherrycl** [comment]
@lenny-intel The [smoke test #61](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-taf-pipelines/job/smoke-test/61/consoleFull) failure for this PR, because we changed the scripts to use Hanoi release build. We reverted the change after adding tag. Now it works fine.

**Comment by lenny-intel** [comment]
> Now it works fine.

Thanks!

**Review by bnevis-i — APPROVED** [review]

**Comment by lenny-intel** [comment]
Waiting on edgexfoundry/edgex-go#2886 before merge

**Review by lenny-intel — APPROVED** [review]

**Pull request merged**
