### PR TITLE
Bump version of postgres container (to 12.1-apline)

### LINKED ISSUE #193: Version bump of postgres for Geneva
Version bump of postgres for Geneva

Cloned from https://github.com/edgexfoundry/edgex-go/issues/1935.

Bump postgres version in docker-compose.
Snaps must be similarly updated.

Version bump is needed to pick up security fixes and reduce technical debt from using out-of-date container versions.

Blackbox regressions must be run against new version.

### PR DESCRIPTION
**Pull request by bnevis-i**
Fixes #193 

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

### CODE REVIEW

**Comment by bnevis-i** [comment]
Blackbox validation results:

-co: 1 failure (same as baseline)
-dv: 137 failures (same as baseline)
-sec: unable to run due to script issue

cd, md, sn, lo, ss, asc tests all pass

**Comment by tingyuz** [comment]
Verified on x86 and confirmed that 12.1-alpine works with kong 2.0.0.rc-1and the proxy is working as expected.

**Comment by bnevis-i** [comment]
In favor of merging this at any time since it is validated for both kong 1.x and kong 2.x.

**Comment by bnevis-i** [comment]
Still awaiting approval.

**Pull request merged**
