### PR TITLE
fix: Disable App Service Config's version check

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md.

## What is the current behavior?
version check is failing

## What is the new behavior?
Disabled version check
Temporary fix until SDK can be bumped to 2.0.0

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by jim-wang-intel — APPROVED** [review]

**Comment by lenny-intel** [comment]
@cherrycl , I think this is failing due to TAF having ASC (App Service Config) added for export. We need you to disable the version check for that instance of ASC same I have done in the PR. THX!

**Comment by cloudxxx8** [comment]
@jinlinGuan I opened an issue for this.  Please help address it next week.
https://github.com/edgexfoundry/edgex-taf/issues/239

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Pull request merged**
