### PR TITLE
Update device services' image version number

### LINKED ISSUE #199: Update DS image tag to 1.1.1
The latest release of DS is v1.1.1, we should update the image tag(version) to use the latest image.

### PR DESCRIPTION
**Pull request by hahattan**
Fix #199 once 1.1.1 images are built.

### CODE REVIEW

**Comment by hahattan** [comment]
rebased, and make PR out of draft because 1.1.1 images were built on DockerHub.

**Comment by hahattan** [comment]
@tsconn23 go device service images v1.1.1 are ready 
could you please merge this PR to update the docker-compose file ?

thanks

**Comment by hahattan** [comment]
rebased

**Comment by cloudxxx8** [comment]
@tsconn23 @iain-anderson @michaelestrin 
could you please help review and merge this PR?  It's for updating the go device service dot release of fuji
thanks

**Comment by iain-anderson** [comment]
Looks ok but I'm not a committer on developer-scripts

**Pull request merged**
