### PR TITLE
Add docker compose file for secret-store and proxy

### PR DESCRIPTION
**Pull request by tingyuz**
Add docker-compose file for preview 0.5.2

Signed-off-by: tingyu.zeng@rsa.com <tingyu.zeng@rsa.com>

### CODE REVIEW

**Comment by tsconn23** [comment]
@tingyuz Suggest you name the file with the relevant version you're targeting -- e.g. docker-compose-proxy-0.5.2.yml. After the images are tagged for California, then you'll need to create another one for that version (0.6.0) at least according to how the naming scheme is now.

Would it be a good idea to put these in their own folder?

**Comment by tingyuz** [comment]
@tsconn23 i will change the name of the compose file with version added. 
and are you suggesting to put the docker compose file back to security-xxx project repo?

**Comment by tsconn23** [comment]
@tingyuz "are you suggesting to put the docker compose file back to security-xxx project repo?" For now, no. I was just wondering if we shouldn't create a folder inside developer-scripts/compose-files for these -- like a "proxy" folder to keep them separate.

**Comment by tingyuz** [comment]
@tsconn23 we have a folder for each project ( reverse-proxy and vault) to hold the docker compose already, so what you think putting extra copy in the developer-scripts folder as well?

**Comment by tingyuz** [comment]
Will resubmit based on Jim's new compose file.

**Pull request closed without merging**
