### PR TITLE
Issue 82 Add Redis to Docker Compose files

### PR DESCRIPTION
**Pull request by andresrinivasan**
Re: #82 

Updated docker-compose.yml and docker-compose-delhi-0.7.0.yml

### CODE REVIEW

**Comment by jpwhitemn** [comment]
@andresrinivasan and @tsconn23 - I'd prefer to have separate compose files for complete EdgeX - one with Redis and Redis configured services/config (along with Mongo for now until the services are all replaced) and one with mongo and mongo based services/config.  Is that possible?  Otherwise, we are going to need lots of documentation about what to do to use Redis v Mongo.   Andre - do you need any kind of init/bootstrapping when Redis is in use?

**Comment by andresrinivasan** [comment]
Updated per conversation

**Comment by tsconn23** [comment]
@andresrinivasan Does it make more sense for this PR to target the Delhi branch with 0.7.1 images? I don't think we need this in master just yet.

**Comment by andresrinivasan** [comment]
@tsconn23 Please confirm you're asking me to create `docker-compose-redis-delhi-0.7.1.yml` based on the Compose file you sent and remove `docker-compose-redis-delhi-0.7.0.yml`.

Shouldn't I also copy the new `docker-compose-redis-delhi-0.7.1.yml` to `docker-compose.yml` so that Edinburgh gets the latest as well.

**Comment by tsconn23** [comment]
@andresrinivasan Well, these compose files targeting 0.7.0 won't be able to make use of Redis anyway because your code isn't available until 0.7.1. And we can't publish the compose files targeting 0.7.1 until we actually publish the images to Docker Hub. Which means any kind of 0.7.1 docker-compose file needs to be made available just after the release drops.

After the 0.7.1 release, in the Delhi branch I think we can create the `docker-compose-redis-delhi-0.7.1.yml` and make corresponding edits to `docker-compose.yml`. In `master` I think we should wait to make any changes related to this until our strategy becomes clearer as we get closer to the Edinburgh release.

**Comment by jpwhitemn** [comment]
Per comments above and with new Delhi Dot release, I am closing out this PR.

**Pull request closed without merging**
