### PR TITLE
docs: updated readme to indicate archive status

### PR DESCRIPTION
**Pull request by jpwhitemn**
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by jpwhitemn** [comment]
recheck

**Comment by MightyNerdEric** [comment]
@jpwhitemn The "smoke tests" step of the verify job is triggering (which it doesn't seem to have done in the successful master builds), and then seems to be timing out. Since this is being archived anyway, would you like me to go ahead and push the change through with the failing build?

**Comment by jpwhitemn** [comment]
@MightyNerdEric - Eric that would be great to push it through.  We are working on the TAF smoke test issue, but in this case it would not apply/matter.  Thanks,

**Comment by cloudxxx8** [comment]
recheck

**Pull request merged**
